[project]
name = "test-amr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "filecomp>=0.0.3",
    "google-cloud-bigquery>=3.38.0",
    "pandas>=2.3.3",
]
